use std::collections::HashMap;
use std::pin::Pin;

use crate::content::{InputPart, RunOutput};
use crate::errors::ProviderError;
use crate::model::{ModelRef, ProviderId, RunOptions};
use futures::Stream;

/// Normalized request passed from the harness runtime to a provider adapter.
#[derive(Clone, Debug)]
pub struct ProviderRequest {
    /// Unique run id generated by the harness.
    pub run_id: uuid::Uuid,
    /// Session id that owns the run.
    pub session_id: uuid::Uuid,
    /// Selected provider/model.
    pub model: ModelRef,
    /// Optional system prompt.
    pub system_prompt: Option<String>,
    /// User input parts for the run.
    pub input_parts: Vec<InputPart>,
    /// Generic runtime options (timeout, buffer sizing).
    pub options: RunOptions,
    /// Provider-specific request options keyed by provider id.
    pub vendor_options: HashMap<ProviderId, serde_json::Value>,
}

/// Optional metadata returned by a provider when the stream starts.
#[derive(Clone, Debug, Default)]
pub struct ProviderResponseMeta {
    /// Provider request identifier, when available.
    pub request_id: Option<String>,
    /// Model name echoed by the provider, when available.
    pub model: Option<String>,
}

/// Internal provider events that the harness normalizes into `StreamEvent`.
#[derive(Clone, Debug, PartialEq)]
pub enum ProviderEvent {
    /// Incremental text output chunk.
    TextDelta { text: String },
    /// Provider signaled completion. `output` may be `None` for delta-only streams.
    Completed {
        output: Option<RunOutput>,
        finish_reason: Option<String>,
    },
}

/// Boxed async stream of provider events.
pub type BoxProviderEventStream =
    Pin<Box<dyn Stream<Item = Result<ProviderEvent, ProviderError>> + Send + 'static>>;

/// Provider stream and optional startup metadata.
pub struct ProviderStreamHandle {
    /// Event stream emitted by the provider adapter.
    pub stream: BoxProviderEventStream,
    /// Startup metadata about the request/stream.
    pub metadata: ProviderResponseMeta,
}

/// Adapter trait implemented by each vendor integration.
#[async_trait::async_trait]
pub trait ProviderAdapter: Send + Sync {
    /// Stable provider id (for example `openai`).
    fn id(&self) -> ProviderId;

    /// Starts a streaming provider request.
    ///
    /// The adapter should return provider-native events normalized into
    /// `ProviderEvent` values. The harness runtime handles public event ordering
    /// and final aggregation.
    async fn start_stream(
        &self,
        req: ProviderRequest,
    ) -> Result<ProviderStreamHandle, ProviderError>;
}
